In [ ]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from datetime import datetime
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
data=pd.read_csv(r"C:\Users\Rinshu\Downloads\Resume.csv")

In [3]:
data.head(5)

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [4]:
data["Resume_html"][0]

'<div class="fontsize fontface vmargins hmargins linespacing pagesize" id="document"> <div class="section firstsection" id="SECTION_NAME500375979" style="\n      padding-top:0px;\n    "> <div class="paragraph PARAGRAPH_NAME firstparagraph" id="PARAGRAPH_500375979_1_326506904" style="\n      padding-top:0px;\n    "> <div class="name" itemprop="name"> <span class="field fName" id="500375979FNAM1"> </span> <span> </span> <span class="field" id="500375979LNAM1"> HR ADMINISTRATOR/MARKETING ASSOCIATE\n\nHR ADMINISTRATOR</span> </div> </div> </div> <div class="section" id="SECTION_SUMM500375981" style="\n      padding-top:0px;\n    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SUMM500375981"> Summary</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375981_1_326506917" style="\n      padding-top:0px;\n    "> <div class="field singlecolumn" id="500375981FRFM1"> <p align="LEFT"> Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management. </p> <p align="LEFT"> Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.  </p> </div> </div> </div> <div class="section" id="SECTION_HILT500375982" style="\n      padding-top:0px;\n    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_HILT500375982"> Highlights</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375982_1_326509244" style="\n      padding-top:0px;\n    "> <div class="singlecolumn maincolumn"> <table class="twocol"> <tbody> <tr> <td class="field twocol_1" id="500375982SKC11"> <p align="CENTER"> Focused on customer satisfaction</p> <p align="CENTER"> Team management</p> <p align="CENTER"> Marketing savvy</p> <p align="CENTER"> Conflict resolution techniques</p> <br/> </td> <td class="field twocol_2" id="500375982SKC21"> <p align="CENTER"> Training and development</p> <p align="CENTER"> Skilled multi-tasker</p> <p align="CENTER"> Client relations specialist</p> </td> </tr> </tbody> </table> </div> </div> </div> <div class="section" id="SECTION_ACCM500375993" style="\n      padding-top:0px;\n    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_ACCM500375993"> Accomplishments</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375993_1_326506914" style="\n      padding-top:0px;\n    "> <div class="field singlecolumn" id="500375993FRFM1"> <ul> <li> Missouri DOT Supervisor Training Certification</li> <li> Certified by IHG in Customer Loyalty and Marketing by Segment </li> <li> Hilton Worldwide General Manager Training Certification</li> <li> Accomplished Trainer for cross server hospitality systems such as  <b> <u> Hilton OnQ</u> </b> ,  <u> Micros </u> <b> <u> Opera PMS</u> </b> <u> , Fidelio </u> <b> <u> OPERA</u> </b> <u>  Reservation System (ORS)</u> , <b> <u> Holidex</u> </b> </li> <li> Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.</li> </ul> </div> </div> </div> <div class="section" id="SECTION_EXPR500375983" style="\n      padding-top:0px;\n    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EXPR500375983"> Experience</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375983_1_326506906" itemscope="" itemtype="https://schema.org/Organization" style="\n      padding-top:0px;\n    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT1"> HR Administrator/Marketing Associate\n\nHR Administrator</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD1"> Dec 2013</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT1"> Current</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP1" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT1" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA1" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES1" itemprop="description"> <ul> <li> Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.</li> <li> Prepares employee separation notices and related documentation</li> <li> Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.</li> <li> Advises management in appropriate resolution of employee relations issues.</li> <li> Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.</li> </ul> <br/> <p align="LEFT"> <b> Marketing Associate</b> \xa0</p> <ul> <li> Designed and created marketing collateral for sales meetings, trade shows and company executives.</li> <li> Managed the in-house advertising program consisting of print and media collateral pieces.</li> <li> Assisted in the complete design and launch of the company\'s website in 2 months.</li> <li> Created an official company page on Facebook to facilitate interaction with customers.</li> <li> Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_2_326506907" itemscope="" itemtype="https://schema.org/Organization" style="\n      padding-top:10px;\n    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT2"> Advanced Medical Claims Analyst</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD2"> Mar 2012</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT2"> Dec 2013</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP2" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT2" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA2" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES2" itemprop="description"> <ul> <li> Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.</li> <li> Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.</li> <li> Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_3_326506908" itemscope="" itemtype="https://schema.org/Organization" style="\n      padding-top:15px;\n    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT3"> Assistant General Manager</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD3"> Jun 2010</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT3"> Dec 2010</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP3" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT3" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA3" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES3" itemprop="description"> <ul> <li> Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.</li> <li> Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.</li> <li> Handled daily operations and reported directly to the corporate office.</li> <li> Hired and trained staff on overall objectives and goals with an emphasis on high customer service.</li> <li> Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_4_326506910" itemscope="" itemtype="https://schema.org/Organization" style="\n      padding-top:5px;\n    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT4"> Executive Support / Marketing Assistant</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD4"> Jul 2007</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT4"> Jun 2010</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP4" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT4" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA4" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES4" itemprop="description"> <ul> <li> Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.</li> <li> Managed front-end operations to ensure friendly and efficient transactions.</li> <li> Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.</li> <li> Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_5_326506911" itemscope="" itemtype="https://schema.org/Organization" style="\n      padding-top:10px;\n    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT5"> Reservation &amp; Front Office Manager</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD5"> Jun 2004</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT5"> Jul 2007</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP5" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT5" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA5" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES5" itemprop="description"> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_6_326506912" itemscope="" itemtype="https://schema.org/Organization" style="\n      padding-top:10px;\n    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT6"> Owner/ Partner</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD6"> Dec 2001</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT6"> May 2004</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP6" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT6" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA6" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES6" itemprop="description"> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500375983_7_326506913" itemscope="" itemtype="https://schema.org/Organization" style="\n      padding-top:10px;\n    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="500375983JTIT7"> Price Integrity Coordinator</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="500375983JSTD7"> Aug 1999</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="500375983EDDT7"> Dec 2001</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="500375983COMP7" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="500375983JCIT7" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="500375983JSTA7" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="500375983JDES7" itemprop="description"> </span> </div> </div> </div> <div class="section" id="SECTION_EDUC500400498" style="\n      padding-top:0px;\n    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EDUC500400498"> Education</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500400498_1_326523310" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="\n      padding-top:0px;\n    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="500400498DGRE1" itemprop="name"> N/A</span> <span> , </span> <span class="programline" id="500400498STUY1"> Business Administration</span> <span class="datesWrapper"> <span class="jobdates" id="500400498GRYR1"> 1999</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="500400498SCHO1" itemprop="name"> Jefferson College</span> <span>  － </span> <span class="joblocation jobcity" id="500400498SCIT1"> City</span> <span> , </span> <span class="joblocation jobstate" id="500400498SSTA1"> State</span> <span class="joblocation jobstate" id="500400498SCNT1"> </span> </span> <span class="field" id="500400498FRFM1"> <ul> <li> Business Administration</li> <li> Marketing / Advertising</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_500400498_2_326522471" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="\n      padding-top:0px;\n    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="500400498DGRE2" itemprop="name"> High School Diploma</span> <span> , </span> <span class="programline" id="500400498STUY2"> College Prep. studies</span> <span class="datesWrapper"> <span class="jobdates" id="500400498GRYR2"> 1998</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="500400498SCHO2" itemprop="name"> Sainte Genevieve Senior High</span> <span>  － </span> <span class="joblocation jobcity" id="500400498SCIT2"> City</span> <span> , </span> <span class="joblocation jobstate" id="500400498SSTA2"> State</span> <span class="joblocation jobstate" id="500400498SCNT2"> </span> </span> <span class="field" id="500400498FRFM2"> <ul> <li> Awarded American Shrubel Leadership Scholarship to Jefferson College</li> </ul> </span> </div> </div> </div> <div class="section" id="SECTION_SKLL500375994" style="\n      padding-top:0px;\n    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SKLL500375994"> Skills</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_500375994_1_326506918" style="\n      padding-top:0px;\n    "> <div class="field singlecolumn" id="500375994FRFM1"> <p align="LEFT"> Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.</p> </div> </div> </div> </div>'

In [5]:
data["Resume_str"][2276]

'         8TH GRADE LANGUAGE ARTS TEACHER       Summary      Teacher with excellent communication skills. Organized and driven with the innate ability to stay on task. Uses effective and efficient methods of teaching while focusing on the individual needs of each student. Seeking a position that will be both challenging and fulfilling.         Highlights           Lesson planning expertise    Academic performance evaluations  IEP familiarity  504 familiarity  Behavioral disorders knowledge       Certified Student Teacher Trainer    Tutoring experience    MS Office proficient    Standardized testing    Google Drive familiarity             Accomplishments      Achieved high growth on 2013-2014 school year End of Grade Assessment for Reading.   Chosen to be an assessment creator for the North Learning Community in Charlotte Mecklenburg Schools, based on high growth for 2013-2014 End of Grade assessment scores.   Helped more than 75%\xa0students reach their Individual Education Program goals.       Chaperoned the 8th\xa0grade trip to The Outer Banks\xa0with 120\xa0students.          Education     2013       Teaching Middle Grades Language Arts    University of North Carolina at Charlotte   －   City  ,   State  ,   U.S.           2011     Bachelor of Arts  :   English    University of North Carolina at Charlotte   －   City  ,   State  ,   U.S.     English Major  Journalism/Sociology Minor         Teaching Experience     04/2013   to   Current     8th Grade Language Arts Teacher    Company Name   －   City  ,   State       Attend professional development, communications with parents, assessments of students, and staff meetings.    Teach high level Talent Development Students English 1 level course work.    Lead 8th grade ELA Professional Learning Community     Establish and maintain positive relationships with students, parents, and colleagues    Teach students that are academically struggling and in need of a small classroom setting for successful development.          10/2013   to   05/2016     6th/8th Grade Language Arts Tutor    Company Name   －   City  ,   State      Provided students with an academically enriched opportunity that addresses core skills for mastery level performance.  Helped bridge the academic gap documented by school assessments.  Enhanced student skill and overall academic success at Ridge Road.          Professional Leadership     10/2015   to   Current     Advisor    Company Name   －   City  ,   State      Create an outlet and social transitional aid for Ridge Road\'s 8th Grade ladies, heading to high school.  Cover common issues that the young ladies face daily such as; health, fitness, daily troubles, social media, self advocacy, public speaking, and studies.  Award participants with awards, scholarships, and gifts from the community sponsors.         08/2015   to   Current     Company Name   －   City  ,   State      Help to improve lines of communication and to promote a free exchange of ideas to facilitate the educational process in the school buildings.  Address issues of common concern in the building, including but not limited to discipline, scheduling, money collection, health and safety, and professional employees doing administrative duties.  Submit a quarterly report of all meetings and recommendations to the staff in the building.         08/2015   to   Current     Teacher Leader    Company Name   －   City  ,   State      Facilitate the involvement of the school community in the development of the School Improvement Plan   Encourage, support and create opportunities for involvement from parents in the community   Contribute to the design of the School Improvement Plan   Monitor the effectiveness of the School Improvement Plan   Use data as the driving force to create programmatic instructional change   Facilitate communication within the Professional Learning Community         08/2015   to   Current     Advisor    Company Name   －   City  ,   State      Work with and through Student Leaders to carry out a phase of their civic education and enhance their leadership skills   Serve as a resource person, a leader to all the members of the Student Council   Build and develop Student Council Members Leadership skills in areas such as communication, goal setting, team building, time management, group dynamics, diversity, problem solving, and project planning   Help to mold attitudes and character of Student Leaders Professional Development.         06/2015   to   Current     Teacher Leader    Company Name   －   City  ,   State      Coordinate the improvement of instruction of the school based on data.  Serve in an advisory capacity to the principal/director and support the development and implementation of the School Improvement Plan.  Reflect, assess, and plan schools data usage and effectiveness with a focus on student leadership and achievement.          Professional Development     04/2014   to   12/2014     CTI Fellow    Company Name   －   City  ,   State      Enrolled and participated in one of CTI\'s eight multidisciplinary seminars (Visual Storytelling in Young Adult and Children\'s Literature).  Spent the summer reading and researching related curriculum units in which to develop for students.  Created curriculum unit to generate learning beyond the classroom.  Published curriculum unit to CTI and Yale National Initiative websites (Freedom Schools: Exploring Racism, Tolerance, and Prejudice.         03/2016       RCA Educator Trainee    Company Name   －   City  ,   State      Learned ways to increase student engagement, ensure academic rigor, and create a climate and culture that leads to success   Observed master teachers in action   Engaged in dynamic workshops   Discovered how to implement the "Three Pillars of RCA" at my school         05/2014   to   08/2014     Servant Leader Intern    Company Name   －   City  ,   State      Attended National Freedom School Training in Tennessee with interns from around the country and in-town training with Freedom School Partners Set-up, maintain and breakdown classroom space   Served as energetic Harambee\' leaders each day of local program operation  Delivered the Integrated Reading Curriculum to a class of ten or more students for 6 weeks during the summer months, *according to the standards developed by the Children\'s Defense Fund  Served as a leader of afternoon activities and other special events; chaperone field trips  Maintained health and safety standards & accurate records relating to attendance and first aid   Collaborated with the program staff to establish and maintain a positive, supportive and structured environment for the *children entrusted to their care.          Skills    AP Style, MLA Style, CANVAS, goal setting, health and safety standards, instruction, team building, lesson plans, meeting leader, Microsoft Office, Windows Operating Systems, problem solving, project planning, public speaking, Reading, researching, safety, scheduling, seminars, structured, Teaching, time management, websites, workshops   '

In [6]:
data.shape

(2484, 4)

In [7]:
data=data.drop(columns=["Resume_html"])

EXPERIENCE COLUMN

In [8]:
patterns = [
        r'(\d+)\+?\s*(?:years?|yrs?)\s*(?:of)?\s*experience',
        r'experience\s*(?:of|:|-)?\s*(\d+)\+?\s*(?:years?|yrs?)',
        r'(\d+)\+?\s*(?:years?|yrs?)\s*(?:in|as|with)',
        r'total\s*experience\s*[:\-]?\s*(\d+)\+?\s*(?:years?|yrs?)',
        r'(\d+)\s*-\s*\d+\s*(?:years?|yrs?)', 
        r'over\s*(\d+)\s*(?:years?|yrs?)',
        r'(\d+)\+?\s*(?:years?|yrs?)'
    ]
def information(text):
    for p in patterns:
       match=re.search(p,text)
       if match:
           return int(match.group(1))
    return 0

In [9]:
MONTH_NAMES = r'(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|sept|oct|nov|dec)'
data_pattern= re.compile(rf'(?:{MONTH_NAMES}\s+|\d{{1,2}}/)?(\d{{4}})\s*(?:-|–|to)\s*(?:{MONTH_NAMES}\s+|\d{{1,2}}/)?(present|current|\d{{4}})',re.IGNORECASE)
def extract_experience(text):
    match=re.findall(data_pattern,text.lower())
    total_year=0
    for start,end in match:
        start_year=int(start)
        end=end.strip()
        if 'present' in end or 'current' in end:
            end_year = datetime.now().year
        else:
            try:
                end_year = int(end)
            except ValueError:
                continue 
        total_year+=end_year-start_year
    return total_year

In [10]:
def combine_exp(text):
    exp=information(text)
    if exp==0:
        exp=extract_experience(text)
    return exp

In [11]:
data["experience"]=data["Resume_str"].apply(combine_exp)

In [12]:
sample_text = data[data['ID'] == 12413512]['Resume_str'].values[0]
matches = data_pattern.findall(sample_text.lower())
print(matches)

[('2013', '2014'), ('2013', '2014'), ('2013', 'current'), ('2013', '2016'), ('2015', 'current'), ('2015', 'current'), ('2015', 'current'), ('2015', 'current'), ('2015', 'current'), ('2014', '2014'), ('2014', '2014')]

In [13]:
data.sample(5)

,ID,Resume_str,Category,experience
2143,22754014,CONTENT STRATEGIST Summary ...,PUBLIC-RELATIONS,41
2398,94137171,PLANT FULFILLMENT LEADER Summ...,AVIATION,18
578,10501991,BUSINESS DEVELOPMENT REPRESENTATIVE ...,BUSINESS-DEVELOPMENT,37
267,13405733,DIRECTOR OF INFORMATION TECHNOLOGY ...,INFORMATION-TECHNOLOGY,13
1765,30542184,CONSTRUCTION ENGINEERING SUPERVISOR ...,ENGINEERING,20

TEXT PREPROCESSING

In [14]:
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rinshu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rinshu\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [17]:
stop_words=set(stopwords.words("english"))
lemmantize=WordNetLemmatizer()

In [18]:
def text_preprocessing(text):
    text=text.lower()
    text=re.sub(r'[^a-zA-Z\s]',"",text)
    text=re.sub(r'https?://\S+',"",text)
    word=text.split()
    words=[lemmantize.lemmatize(w) for w in word if w not in stop_words]
    return " ".join(words)

In [19]:
data["clean_resume_str"]=data["Resume_str"].apply(text_preprocessing)

In [20]:
data["clean_resume_str"][0]

'hr administratormarketing associate hr administrator summary dedicated customer service manager year experience hospitality customer service management respected builder leader customerfocused team strives instill shared enthusiastic commitment customer service highlight focused customer satisfaction team management marketing savvy conflict resolution technique training development skilled multitasker client relation specialist accomplishment missouri dot supervisor training certification certified ihg customer loyalty marketing segment hilton worldwide general manager training certification accomplished trainer cross server hospitality system hilton onq micros opera pm fidelio opera reservation system or holidex completed course seminar customer service sale strategy inventory control loss prevention safety time management leadership performance assessment experience hr administratormarketing associate hr administrator dec current company name city state help develop policy directs coordinate activity employment compensation labor relation benefit training employee service prepares employee separation notice related documentation keep record benefit plan participation insurance pension plan personnel transaction hire promotion transfer performance review termination employee statistic government reporting advises management appropriate resolution employee relation issue administers benefit program life health dental insurance pension plan vacation sick leave leave absence employee assistance marketing associate designed created marketing collateral sale meeting trade show company executive managed inhouse advertising program consisting print medium collateral piece assisted complete design launch company website month created official company page facebook facilitate interaction customer analyzed rating programming feature competitor evaluate effectiveness marketing strategy advanced medical claim analyst mar dec company name city state reviewed medical bill accuracy treatment test hospital stay prior sanctioning claim trained interpret code icd cpt terminology commonly used medical billing fully understand paperwork submitted healthcare provider required organizational analytical skill well computer skill knowledge medical terminology procedure statistic billing standard data analysis law regarding medical billing assistant general manager jun dec company name city state performed duty including limited budgeting financial management accounting human resource payroll purchasing established maintained close working relationship department hotel ensure maximum operation productivity morale guest service handled daily operation reported directly corporate office hired trained staff overall objective goal emphasis high customer service marketing advertising working public relation medium government local business chamber commerce executive support marketing assistant jul jun company name city state provided assistance various department head executive marketing customer service human resource managed frontend operation ensure friendly efficient transaction ensured swift resolution customer issue preserve customer loyalty complying company policy exemplified secondtonone customer service delivery interaction customer potential client reservation front office manager jun jul company name city state owner partner dec may company name city state price integrity coordinator aug dec company name city state education na business administration jefferson college city state business administration marketing advertising high school diploma college prep study sainte genevieve senior high city state awarded american shrubel leadership scholarship jefferson college skill accounting ad advertising analytical skill benefit billing budgeting client customer service data analysis delivery documentation employee relation financial management government relation human resource insurance labor relation layout marketing marketing collateral medical billing medical terminology office organizational payroll performance review personnel policy poster presentation public relation purchasing reporting statistic website'

TF IDF

In [21]:
tf=TfidfVectorizer()
job_desc=input("enter your requirements:")
cleaned_job_des=text_preprocessing(job_desc)
cleaned_jd=data["clean_resume_str"]
corpus=[cleaned_job_des] + cleaned_jd.tolist()

result=tf.fit_transform(corpus).toarray()

In [22]:
result

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
jd_vector=result[0].reshape(1,-1)
clean_vector=result[1:]

similarity=cosine_similarity(jd_vector,clean_vector).flatten()

In [26]:
data["similarity"]=similarity*100
top_matches=data.sort_values(by="similarity",ascending=False).head(10)
top_matches.head(3)

,ID,Resume_str,Category,experience,clean_resume_str,similarity
22,25676643,HR SPECIALIST Summary An Hum...,HR,9,hr specialist summary human resource specialis...,5.369108
40,41523474,HR EXECUTIVE Summary Dual s...,HR,1,hr executive summary dual specialization domai...,3.971755
2026,32773331,PROJECT ENGINEER & PROJECT MANAGER ...,CONSTRUCTION,20,project engineer project manager summary const...,3.811200